### ISSUE TITLE
Must bash be required?

### ISSUE THREAD

**Issue by gaggle** [geelen/shellac#6]
I wanted to use shellac in an alpine Docker image but it doesn't have bash, just shell. I just wanted to naively ask if there is a world where you see shellac working with that?

**Comment by geelen** [comment]
Potentially, sure! Would there be many inconsistencies between Bash and Shell we'd need to watch out for?

**Comment by gaggle** [comment]
Oof, that's a good question. I haven't gotten the test-suite working when cloning shellac so I haven't made my own tests, and I'm certainly not a shell expert enough to know in advance what difficulties it may cause.

In hindsight this question probably wasn't suited for a Github issue, should've been a tweet or something, because I have nothing to bring to the table other than an unsolicited feature-request :)

Feel free to close, is what I'm saying :)
